services:
  todo-frontend:
    build:  ./todo-frontend
    ports:
      - "3000:80"
    networks:
      - todo-network
    depends_on:
      - todo-backend

  todo-backend:
    build: ./todo-backend
    ports:
      - "3002:3002"
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge