#SPDX-License-Identifier: MIT-0
---
# tasks file for common
- name: Set platform-specific package list
  set_fact:
    package_name:
      - "{{ apache_package_name[ansible_distribution] }}"
      - "{{ node_package_name[ansible_distribution] }}"
      - git
      - docker.io
- name: Install Common Packages
  become: true
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop: "{{ package_name }}"

- name: Ensure rsync is installed (required for synchronize)
  become: true
  apt:
    name: rsync
    state: present

- name: Start and enable Apache
  become: true
  service:
    name: apache2
    state: started
    enabled: yes

- name: Ensure target directory exists on EC2
  become: true
  file:
    path: /opt/todo-app
    state: directory
    mode: '0755'

- name: Copy source code from GitHub runner to EC2
  become: true
  synchronize:
    src: "{{ playbook_dir | realpath }}/../../"
    dest: "/opt/todo-app"
    delete: yes
    recursive: yes
    rsync_opts:
      - "--exclude=.git"
      - "--exclude=.github"
      - "--exclude=ansible"
    rsync_path: "sudo rsync"
    _ssh_args: "-i {{ ec2_ssh_key_path }} -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
  delegate_to: localhost




